name: ❓ Question
description: Ask a question about the project
title: "[QUESTION] "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ❓ Question
        
        Have a question about the project? We're here to help! Please provide as much context as possible.
        
        ---

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please check these first
      options:
        - label: I have searched existing issues and discussions for my question
          required: true
        - label: I have checked the documentation and README
          required: true
        - label: This is not a bug report or feature request
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What type of question is this?
      options:
        - Usage - How to use the project
        - Configuration - Setup and configuration help
        - Troubleshooting - Something isn't working as expected
        - Best Practices - Recommended approaches
        - Integration - How to integrate with other tools
        - Architecture - Understanding the project structure
        - Contributing - How to contribute to the project
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please ask your question clearly and provide context...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to achieve? What have you tried so far?
      placeholder: |
        Please provide context:
        - What are you trying to accomplish?
        - What have you already tried?
        - What resources have you consulted?
        - Any relevant background information

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: If your question is environment-specific, please provide details
      placeholder: |
        - OS: [e.g., Windows 11, macOS 12.0, Ubuntu 20.04]
        - Framework Version: [e.g., .NET 6.0, Node.js 16.0]
        - Project Version: [e.g., v1.2.3, latest]
        - Additional tools: [e.g., Docker, VS Code]

  - type: textarea
    id: expected
    attributes:
      label: Expected Outcome
      description: What result or answer are you hoping for?
      placeholder: Describe what you expect or what success looks like...

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 🤝 Getting Help
        
        **Quick Response?** For faster answers, you might also try:
        - 📖 [Documentation](../README.md)
        - 💬 [Discussions](../../discussions)
        - 🔍 [Search existing issues](../../issues)
        
        **Community Support**: Our community is always happy to help each other out!
